### ISSUE TITLE
[FEAT] Define ResponseHandler

### ISSUE THREAD

**Issue by seushin** [WeCanWebserv/Webserv#10]
## Description
- 데이터를 표현하는 Response 객체에서 Request를 처리하는 로직을 분리하고자 만들었어요
- 멤버로 Response를 가지게 되어 메소드들을 감싸는 구조를 생각중이에요
- 결과적으로 `request-target`에 대한 처리와 에러 페이지에 대한 처리를 제공하는 게 목표에요
- cgi에 대해서는 우선 다루지 않으려 해요
- 제가 방향을 잘못 생각하고 있다면 알려주세요...

## TO DO
- [ ] 작성중

**Comment by kimhxsong** [comment]
Response 클래스에서 Request를 처리하는 로직을 넣어도 괜찮지 않을까? 라는 의견입니다만.


Response 객체에서 Request를 처리하는 로직을 분리하고자 한다면, 멤버로 Response를 가지는 것보다는 RequestHandler의 멤버 함수를 구현할 때 인자를  Request 타입 창조자로 받도록 하는 것은 어떨까요? 이 경우 RequestHandler 타입의 객체가 ServerManager의 데이터 멤버로 추가돼야 할 것 입니다.


Response는 Connection의 수 만큼 존재해야 하겠으나  ResponseHandler가 Connection 수 만큼 생성될 것을 상상하면 조금 어색하게 느껴지는 것 같습니다.  Handler가 구현되면 stringstream 타입의 response buffer가 Response가 아닌 RequestHandler에 넣고자 하는 계획일까요?

**Comment by seushin** [comment]
아무래도 어색한 부분이 있는 것 같네요. Response 객체에 기능을 넣는 쪽으로 해보겠습니다!
버퍼에 대한 고민이라기 보다 static file, directory listing, error page, cgi에 대한 변수들과 로직들이 Response를 너무 장황하게 만들지 않을까 하는 걱정이었습니다. 근데 다시 생각해보니 괜찮을 것 같아요.
