### ISSUE TITLE
[Fix] 오류 수정

### ISSUE THREAD

**Issue by seushin** [WeCanWebserv/Webserv#46]
## Description
wordpress를 돌려보겠다는 꿈을 가지고 테스트 하다 수정할 것들을 조금 찾았습니다. 

## Regular file
- [x] epoll_ctl 에서 또다시 에러(operation not permitted)가 발생합니다...  따라서 파일을 fstream으로 관리하고 이벤트 등록은 하지 않으려 합니다. (다만 고치더라도 가장 나중에 수정하겠습니다)

## autoindex
- [x] stat 인자 path가 config.root를 포함하도록 수정합니다.

## Cgi
- [x] 파이프의 EOF 이벤트는 EPOLLIN에서 0 byte를 read 하는 것이 아닌 EPOLLHUP 이벤트를 통해 확인해야 합니다. (파이프가 닫혀도 EPOLLIN이 발생하지 않더라구요)
- [x] 환경변수 배열에 누락된 널 포인터를 추가합니다.
- [x] 파이프의 논블락 설정을 fork 이전에 설정합니다.
- [ ] 파이프가 닫히면 프로세스의 종료값을 wait로 확인합니다.
- [ ] index file이 서버에 의해 추가된 경우를 고려합니다.
- [ ] 리다이렉션을 올바르게 처리합니다.

## Config
- [x] isRedirectionSet, isAutoIndexOn의 기본값을 false로 설정합니다.

## Request
- [x] RequestManager.pop이 queue에서 pop한 요소를 참조하여 abort가 발생합니다. Request를 값으로 반환하는게 어떨까 싶습니다!
- [x] cgi 스크립트에 전달하기 위해 header.FieldValue를 string으로 받을 수 있으면 좋을 것 같습니다.

**Comment by jungcow** [comment]
헛... pop으로 지우고 반환을 해서 레퍼런스가 참조하는 객체가 사라졌던 것 같습니다... 복사 생성자가 이제 있으니깐 그렇게 해야 맞는 것 같네요..
